trigger: none
pr: none
pool:
  vmImage: 'windows-latest'

resources:
  webhooks:
    - webhook: wh_payload
      connection: TeamProjectName
      filters:
        - path: repo
          value: $(Build.Repository.Name)

name: $(Date:yyyyMMdd).$(Rev:r)_${{ parameters.wh_payload.branch}}_${{ parameters.wh_payload.action}}

extends:
  template: envdevops.yml
  parameters:
    wh_payload:  ${{ parameters.wh_payload }}
                           

    