#push.yml


parameters:
  - name: wh_payload
    type: object
    default:
  - name: SourceBranch
    type: string
    default: not-specified
  - name: Push2Branch
    type: string
    default: not-specified

steps:
- script: echo Running push2next.yml


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "pushing to ${{ parameters.Push2Branch }}"

      git push origin ${{ parameters.SourceBranch }}:${{ parameters.Push2Branch }}

      exit 0      

    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Push-2-Next'