trigger: none
pr: none
pool:
  vmImage: 'windows-latest'

resources:
  webhooks:
    - webhook: project.1
      connection: project.1
      filters:
        - path: repo
          value: reponame.1

name: $(Date:yyyyMMdd).$(Rev:r)_${{ parameters.project.1.branch}}_${{ parameters.project.1.action}}

extends:
  template: templates/envdevops.yml
  parameters:
    wh_payload:  ${{ parameters.project.1 }}